-keepattributes *Annotation*
-keep class com.example.browser.data.model.** { *; }
-keep class com.example.browser.data.local.entity.** { *; }
-keep class com.example.browser.data.local.dao.** { *; }
-keep class com.example.browser.data.local.BrowserDatabase { *; }
