package com.example.browser.web

object AdBlocker {
    private val adDomains = setOf(
        "pagead2.googlesyndication.com",
        "adservice.google.com",
        "www.googleadservices.com",
        "googleads.g.doubleclick.net",
        "stats.g.doubleclick.net",
        "ad.doubleclick.net",
        "static.doubleclick.net",
        "adclick.g.doubleclick.net",
        "ads.youtube.com",
        "s.youtube.com",
        "ad.youtube.com",
        "ads-twitter.com",
        "analytics.twitter.com",
        "ads.facebook.com",
        "pixel.facebook.com",
        "analytics.facebook.com",
        "ads.linkedin.com",
        "ads-api.tiktok.com",
        "analytics.tiktok.com",
        "ad.atdmt.com",
        "ads.yahoo.com",
        "adserver.yahoo.com",
        "advertising.com",
        "adtech.de",
        "adform.net",
        "adnxs.com",
        "adsrvr.org",
        "adsymptotic.com",
        "adtechus.com",
        "amazon-adsystem.com",
        "analytics.edgekey.net",
        "app-measurement.com",
        "betrad.com",
        "bounceexchange.com",
        "chartbeat.com",
        "chartbeat.net",
        "clicktale.net",
        "clkads.com",
        "connatix.com",
        "contextweb.com",
        "cpx.to",
        "crwdcntrl.net",
        "demdex.net",
        "doubleverify.com",
        "ensighten.com",
        "exelator.com",
        "eyeota.net",
        "facebook.com/tr",
        "fastclick.net",
        "flashtalking.com",
        "fwmrm.net",
        "gemius.pl",
        "google-analytics.com",
        "googlesyndication.com",
        "googletagmanager.com",
        "googletagservices.com",
        "gravatar.com",
        "gstatic.com/gen_204",
        "heapanalytics.com",
        "hotjar.com",
        "imrworldwide.com",
        "indexww.com",
        "inspectlet.com",
        "ipredictive.com",
        "krxd.net",
        "lijit.com",
        "liveintent.com",
        "loading-delivery1.com",
        "magnify360.com",
        "mathtag.com",
        "maxymiser.net",
        "media.net",
        "moatads.com",
        "mookie1.com",
        "msecnd.net",
        "netmng.com",
        "newrelic.com",
        "narrativ.com",
        "nativo.com",
        "nr-data.net",
        "omtrdc.net",
        "optimizely.com",
        "outbrain.com",
        "pardot.com",
        "parsely.com",
        "permutive.com",
        "pippio.com",
        "pixanalytics.com",
        "pixel.adsafeprotected.com",
        "popads.net",
        "popcash.net",
        "pubmatic.com",
        "quantserve.com",
        "revjet.com",
        "rfihub.com",
        "rlcdn.com",
        "rndcdn.com",
        "rubiconproject.com",
        "sail-horizon.com",
        "scorecardresearch.com",
        "segment.com",
        "sharethrough.com",
        "smartadserver.com",
        "snapads.com",
        "spotxchange.com",
        "stickyadstv.com",
        "taboola.com",
        "tapad.com",
        "tidaltv.com",
        "trafficjunky.com",
        "tribalfusion.com",
        "turn.com",
        "undertone.com",
        "vungle.com",
        "yieldmo.com",
        "zedo.com",
        "zergnet.com",
    )

    private val adPaths = listOf(
        "/ads/",
        "/ad/",
        "/adserver/",
        "/advert/",
        "/banner/",
        "/banners/",
        "/popup/",
        "/popunder/",
        "/tracking/",
        "/pixel/",
    )

    fun isAd(url: String): Boolean {
        val lower = url.lowercase()
        try {
            val host = java.net.URI(url).host?.lowercase() ?: return false
            if (adDomains.any { host == it || host.endsWith(".$it") }) {
                return true
            }
            if (adPaths.any { lower.contains(it) }) {
                return true
            }
        } catch (_: Exception) {
            // ignore malformed URLs
        }
        return false
    }
}
